services:
  - type: web
    name: bookmyheart-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
      - key: PB_ENCRYPTION_KEY
        generateValue: true
    disk:
      name: pb-data
      mountPath: /pb_data
      sizeGB: 1